[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.5.1"
torchvision = "^0.20.1"
wandb = "^0.18.6"
timm = "^1.0.11"
scipy = "^1.14.1"
open-clip-torch = "2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
